api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    collection:
        pagination:
            enabled: false
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
